spring:
  application:
    name: hotsix

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ssafy?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
      username: ssafy
      password: ssafy
      pool-name: hikari-pool
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/

  output:
    ansi:
      enabled: always

  kafka:
    producer:
      properties:
        auto.create.topics.enable: true

logging:
  level:
    com:
      ssafy: debug
  pattern:
    console: '%clr(%d{HH:mm:ss} [%-5level] %c{20}.%M.%L: %m%n)'

file:
  upload-dir: C:/upload/img/
  path:
    upload-images: C:/board/upload/imageUpload
    upload-files: C:/board/upload/fileUpload/

jwt:
  salt: our-screte-key-20240514-Lim-Dong-Gil-Kang-Min-Seo
  refresh-token:
    expiretime: 2592000000
  access-token:
    expiretime: 3600000
